FROM eclipse-temurin:17-jre

# SECURITY: add a non-privileged linux user
RUN useradd -ms /bin/bash cloudchaser
USER cloudchaser

# create & change working directory
WORKDIR /app

# script variables + env args, or secrets, etc
ARG JAVA_OPTS
ENV JAVA_OPTS=$JAVA_OPTS

# copy the "fat jar" to current "/app" directory
COPY target/*.jar app.jar

# expose ports to outside world
EXPOSE 8080

# start the app
ENTRYPOINT exec java $JAVA_OPTS -jar app.jar
